import Link from 'next/link'
import './globals.css'
import { Inter } from 'next/font/google'
import LoginBtn from './loginBtn'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/pages/api/auth/[...nextauth]'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  let session = await getServerSession(authOptions)

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='navbar'>
          <div className='nav-item'>
            <Link href="/" className='logo'>JoyForum</Link>
            {session && <Link href="/list">List</Link>}
          </div>
          <LoginBtn session={session}/>
        </div>
        {children}
      </body>
    </html>
  )
}
